// Program: Doogal Bot
// Author: Jacob Rutkowski
// Purpose: GroupMe Bot that sends quotes from Doogal in the 2005 film 'Doogal' at random and on command.
// Last Updated: 6/2/21

// Global Variables
var botId = "Insert your Bot ID here";
var groupId = "Insert your Group ID here"
var accessToken = "Insert your Access Token here";

// Doogal Quotes
var script = ["Ooh!",
"Oh, I'm going to be late!",
"Shoot.",
"Hello, Florence.",
"The what?",
"The opera concert? Oh, yeah. Yes, Florence, of course. I wouldn't miss it for the world.",
"Candy? Who needs candy? Ha! Not me, I quit. This morning!",
"Oh no!",
"Not again.",
"Florence!",
"Oh, dear, oh, dear, oh, dear. Oh, man, would you look at that? What an unforeseeable accident! That's not an easy fix, that. We're looking at a multiple abrasion friction gash.",
"Of course! If you bring me an air pump, some glue, four watermelons, water-skis, a trombone, and a pack of jawbreakers, I might just be able to help you out.",
"By the way, I was the one who deflated the tire. Sorry about that.",
"Oh, I'm so going to take care of them all right.",
"Mmmm...I think I'll take care of those lollipops first, and then, ooh, those sherbets and, ooh-ooh-ooh, those caramel creams. Afterwards, I’ll take care of these candy canes, and then these jelly beans! Oh, Doogal's in heaven!",
"Wahhh! Aghhhh!",
"Wahhhhh!",
"Agh! Agh! Agh! Oooh! Oooh! Wahhhhh!",
"Get me off! How do I stop this thing?! Where are the brakes?! Please, help me!",
"Agh! Agh! Help! Wahhhh!",
"Ooh! Wh-what's happening?",
"Oh, no! Florence!",
"Florence! Are you all right?",
"Don't worry, Florence. We'll get you out of there.",
"Zebedee! Zebedee! Zebedee!",
"I destroyed the carousel.",
"What? Tuesday? But Tuesdays are great! On Tuesdays, we make cake.",
"Zeebad? I thought he was fake like wrestling.",
"Oh my! Well, freezing the world by freezing the sun sounds like a bad thing to me.",
"Oh, dear. This isn't good.",
"Florence, hold on. We'll find those diamonds and get you out of there. I'll be back. I promise.",
"Huh? Guys!",
"Oh, Florence... I'm so sorry.",
"Yeah?",
"Me?!",
"My fault? What did I do?!",
"Oh, yeah. That, too. I'm sorry for everything I did.",
"No, I don't! And I'm not gonna rest until I've done everything in my power to make things right!",
"Aww!",
"Oh well. I guess that means we'll have to make camp for the night. (turns to his friends) What do you think, guys? Shall we take a break?",
"Good! Now it's settled. Guys, let's set up our tents.",
"Just a little bit of sugar! Perfect!",
"Hey, guys. What's for dinner? I'm famished.",
"Oh, I see. The silent treatment, is it? Huh! Well, fine! Dylan and I got our own camps over here, and they’re awesome. We don't need you guys. Luckily, I brought some secret supplies. Mm.",
"Uh oh!",
"My gobstoppers! Oh, no! There's only one left!",
"Someone should keep watch, and I was thinking if I could protect this campsite from Zeebad.",
"What? Sweet!",
"Eh? What?",
"Wait! Wait! Oh!",
"Alright, guys. It’s time for me to protect our camp.",
"Look at me. I'm all alone, guarding against the cold. Why do I have to be the watchdog? What's wrong with a watchsnail, or a watchcow, or a...?",
"Who goes there? Friend or foe or... (sees the blue moose) moose? F-feeling a bit blue?",
"Huh?",
"Hey! Calm down. You're not the only creature who is blue. There are lots of blue creatures here on planet Earth. The blue jay is one of those creatures.",
"Well, the other blue creature here would have to be... Zeebad. You’d hate to mess with him. He is definitely someone who wants to freeze you.",
"Unfortunately, it isn't. He is that blue, scary, and cold jack-in-a-box-like wizard that you're referring to. Not only that, but he's also Zebedee's evil clone. 10,000 years ago, Zeebad tried to keep the world frozen forever but he got attacked and imprisoned by Zebedee. And now that I've released him by accident, he's free to wield his terrifying power once again, and boy, is this going to get ugly. You must avoid him at all costs. Do you understand?",
"Good. Oh, and like I said before, you're not the only creature who is blue.",
"Ooh! Is this a friend of yours?",
"Huh? Oh, yes. Sure. Go ahead.",
"I'll take that as a no.",
"Not so fast, Zeebad!",
"Yah!",
"Where am I?",
"It's really good to see you, Zeebad. I'm Doogal.",
"You're gonna be in huge trouble when Zebedee gets here.",
"Well, I was a very happy puppy. My first memories are of catching tennis balls with Florence. And then, as I grew up, I got along with everyone in the town. I even had a dream of being in some sort of sugar paradise with her. Doesn't that sound like a really good story?",
"Me? Well, you're wasting your time. I don't know anything. I don't even have a map.",
"Oh! Uh...no, no, no, no, no! No map.",
"I'll never tell you who has the map, so forget it, Frosty!",
"Oh, uh...hmm.",
"Oh, this is awful! No! No more!",
"Oh! No more! Please!",
"Oh! I can't stand it!",
"You'll have to make me eat 100 before I tell you anything! Ahh.",
"This is terrible! I won't let you!",
"No, you mustn't!",
"Please! No more!",
"Huh? Ohh! Ow! Ohh! I can't feel my paws!",
"No! Leave me alone, you evil, evil fiend!",
"Could you come back in five minutes? I think I can get some lollipops out of him.",
"Come on, guys. Let's keep moving. Keep going. Keep going.",
"Zebedee! Zebedee! Zebedee!",
"Ohh! Wait for me!",
"Zebedee, look out!",
"Stop! Wait! Zebedee's in trouble!",
"What shall we do? What shall we do?",
"Noooo!",
"Oh no! No! No! No, no. He's... he's gone. He... he sacrificed himself... for me. That... that should have been me! I should have been the one to be dead, not him! Noooo! He's gone for good.",
"But Zebedee's magic is the only thing that can stop Zeebad. And now who's going to help Florence and the children?",
"No! Brian's right! We're going to save our world. Dylan, where's the map?",
"That's the spirit, everyone! It would take a sea of boiling lava to keep us from those diamonds now!",
"Oh no! No way!",
"Uh, well, diamonds are a girl's best friend. Off you go, Ermintrude.",
"Well, all dogs like to fetch, but not me. The only tricks I know are, 'Sit, Doogal.', and, 'Stay, Doogal, stay.'",
"Huh?",
"I think I ought to keep a lookout for another entrance here while you guys cross to the other side.",
"Hmm? All right, all right, I understand. You don't want to go without your leader.",
"No, I’m just a little uncomfortable about being on a crumbling bridge over a lake of boiling lava.",
"Easy does it.",
"Careful!",
"Aah!",
"Aah! Aah! Nooo!",
"Up! Pull us up!",
"Can't one of you just hop out and push? Give it some gas!",
"Brilliant.",
"Guys! Hey, guys, over here! Hurry up! I think I see it!",
"And there you have it. It took a while, but... we have found the first diamond.",
"Dylan, do the honors, would ya?",
"Look! It's... it's Florence!",
"She can hear me. Florence! It's me, Doogal! I've come to save you!",
"Oh, no, she's fading. No, come back!",
"Florence!",
"I can't believe Florence is still stuck in the carousel along with the other two children. Not only is Florence my owner, but she's also my best friend. It's only been one day and the children are freezing fast.",
"I'm the one who told him.",
"But they tortured it out of me. That has to be a crime!",
"You're a despicable fiend.",
"I don't think so, Dylan. At least we'll be nice and warm.",
"You are big.",
"Of course!",
"Just press the darn button!",
"A battleship. Great. And now we'll just sail away on the boiling lava. Then we can chase after Zeebad and retrieve the map and the first diamond. You guys with me?",
"Sounds like Dylan has been watching too much TV.",
"Brian's right. He’s worried that we could float around here for years!",
"Ha!",
"Seriously. Is that all you ever think about?",
"I can't sleep. I'm too worried about Florence. She's so helpless without me. She must be petrified.",
"Exactly. I calm her down. The truth is, I do everything for her. Her life would be quite empty without me there.",
"During scary thunderstorms, she insists I sleep on the bed with her, for her protection. And she just loves to throw a tennis ball. And who's always there to bring it back, just so that she can have the enjoyment of throwing it again? I'm telling you, Dylan, I bet she really misses that. Really, really. I know I do.",
"Florence? Florence!",
"I love you too, Florence.",
"I don't know about you, but whenever I see ice, that means more chaos from Zeebad and more trouble for the world has yet to come.",
"Okay, everybody, prepare to land!",
"Lower. Lower. Loads of room. Lower.",
"Stop!",
"Huh. Sorry.",
"Just in time for lunch!",
"Whoa!",
"Wait here and keep your pistons pumping. We're gonna need them for a quick getaway.",
"It's probably the ancient equivalent of a welcome mat. They might as well mean 'Aloha' or 'Death to All Who Come Here'.",
"Ooh! Ooh. I’m sorry. Where are my manners? Ladies first.",
"Well, look who's beginning to grow a spine.",
"Ooh!",
"HEY!",
"Does anyone find the diamonds?",
"We must be in the wrong place. Ooh, a throne! The perfect place to enjoy my last gobstopper. Oh, look. A recline button. I wonder what this throne does.",
"Huh? Ooh! Oh no!",
"But I'm chewing my gum. Besides, I'm too hairy.",
"I got this for you. I could give you a piggyback ride towards the diamond and you could knock it off of the claw with your plastic hammer.",
"Sweet moves! That was brilliant!",
"Oops!",
"Ohh! (whimpers) This is not good!",
"Hey! Can you teach me some of that?",
"Er... Ooh.",
"Whee-ee!",
"Hmm. A good group effort. Now, let's grab the diamond and head out.",
"Uh oh.",
"Erm, no, actually. The fearless warrior couldn't make it today so we came instead. We'll drop it in to him on the way home.",
"Oh, well, if you're offering, yes, please.",
"I don't like this! I wish this never happened!",
"Oh, uh... I should have kept my big mouth shut. Aah! Aah! Hey! Hey! Dogs are meant to eat bones, not the other way around!",
"Er, er... Agh!",
"Well, if you keep your cool and try not to freak out, it's amazing what you can do. Now, there's no time for chitchat. Let's grab that diamond and get out of here.",
"Nope.",
"Yeah! That's the last we'll see of them! Huh?",
"Heh heh heh! That took 'em down a batch or two.",
"Really? What is it?",
"No way!",
"That's it! The third diamond is inside the carousel, and according to Zebedee, it's hidden and secure inside the vault, and the vault is at the carousel’s engine control room, which in turn is underneath the carousel itself. It's been right there in the village this whole time!",
"Guys, look!",
"Whoa!",
"Typical train. Always turns up when you least expect it. Come on, gang. In we go.",
"Are you kidding? We're moving at a snail's pace.",
"Behind us!",
"No, look! Behind us!",
"That is the light at the end of the tunnel!",
"We're going to be okay.",
"And while Zeebad's still trapped in the temple, we're actually out of it... and going away from it.",
"Oh no!",
"Whoa!",
"Dylan, watch out!",
"Oh no! Where are we now?",
"Uh, I'll take a Quarter Pounder with Cheese... hold the pickles... with a side order of french fries, a vanilla ice cream cone, a vanilla shake, and chocolate chip cookies. Oh, and I would also like to have one Happy Meal for one of my friends, please.",
"We've gotta get rid of them!",
"Oh, crud! Zeebad's back! Faster!",
"Brian!",
"Oh, no!",
"Aah!",
"Aghhhhhhh!",
"Is anyone alright? Brian, are you okay?",
"Yep, I'm fine. Ermintrude, are you okay?",
"Oh, good. Dylan, are you alright?",
"Oh! That's gotta hurt.",
"Hang on, Zeebad doesn't know the diamond is at the carousel.",
"Blaming each other won't solve anything. Now let's get on the train.",
"Are you alright?",
"Oh, the sun is setting!",
"So long, fellow train.",
"Poor Florence and the children. If we don't make it there soon, they'll be frozen solid.",
"Wait. What's that? Look! Footprints! They're fresh, too. Maybe they'll lead us back home.",
"Oh, no. No! No!",
"No. We mustn't sleep. It's too cold. It's too cold. We mustn't. Florence, I promised I would save you. I promised.",
"Florence! Thank god you're okay!",
"What about the carousel? The children are huddled up together. They're freezing.",
"Oh, my god! No! This isn't right! I must be going nuts! I have to wake up and save Florence! Florence! Snap out of it! Florence!",
"No! It was just a dream. Florence...! Florence!",
"Huh? Oh my! It's already morning. I guess I'll have to go wake up my friends about this. Come on! Wake up! Wake up! Wake up! Dylan! You've gotta wake up!",
"Come on, guys! The sun is rising and the sky is getting sunlight, and yet we're still completely lost.",
"Look! Look, look, look! Quick, come and have a look! Look at that! Is that really what I think it is?",
"There's the carousel! Let's get down there and help Florence!",
"No, no, this is definitely it. If we go past this white thingy and by this white bit... just around the corner should be the, er... Oh, no.",
"Zeebad!",
"Florence!",
"Ohh! Oh, no! Florence! Oh, no! No! No! No, no. This is all my fault. If only I hadn't been so greedy and stupid. Oh.",
"Wait a minute! That's it! Ermintrude! Sing! Sing as loud as you can!",
"Yeah, Ermintrude! Sing!",
"Run!",
"Dylan, heads up! Quick!",
"It's coming!",
"Over to me, over to me!",
"Ooh, nice catch, Zeebad. Now it's time for me and my friends to get the final diamond.",
"I called it first.",
"You don't scare me. Why? Because you're just a big, blue bully. The tables have turned. All we need to do is put this last diamond back on the carousel.",
"Shoot.",
"Huh?",
"I got it!",
"It's mine.",
"No. Wait! No, I got it!",
"Train! You made it!",
"Out of the way. I'll get it. I got us into this mess and I will get us out.",
"Chitty chitty chat chat, chitchat.",
"You want your icy, cold, frozen, and snowy world so bad?",
"Then take it! Ya!",
"Hurrah! We did it! We did it! We did it!",
"Come on!",
"I can't believe this. It's over. We defeated Zeebad! We won! We did it! We actually won!",
"Hooray!",
"Touchdown!",
"But where's Florence?",
"Florence?",
"Oh no! Florence! Florence, can you hear me? Please wake up. Please wake up! Don't leave me. This world means nothing without you.",
"No, it can't... She can't... Florence! My best friend Florence! Huh?",
"Oh, Florence, I thought I'd lost you forever!",
"Oh, stop, please. It's what any incredibly heroic dog would do, really.",
"What? Oh, no. I've learned my lesson. I'm not having anything more to do with lollipops. Or gobstoppers. Or toffees.",
"Zebedee! It's good to see you again! I... I missed you. We all do. But... we thought you were dead!",
"Oh, no!",
"Sam? But that's Zeebad's henchman! He tortured me! Now that has to be a crime! We can't trust him.",
"Huh?",
"Huh? Mmm-hmm.",
"Ah! Delicious!",
"Okay, since this is becoming too popular, let me just push this out of the way."]

// Functions

// Function that randomly chooses the next quote from the Doogal script to send to the chat.
function chooseText() {
    return Math.floor(Math.random() * (script.length));
}

// Function that sends text to the chat when needed.
function sendText(text) {
  UrlFetchApp.fetch("https://api.groupme.com/v3/bots/post", {"method":"post", "payload":'{"bot_id":"' + botId + '","text":"' + text + '"}'})                                     
}

// Function that reads in messages from the chat and responds if certain circumstances are met.
function doPost(e){
  var post = JSON.parse(e.postData.getDataAsString());
  var text = post.text;
  var user_id = post.user_id;
  var randomNum = Math.floor(Math.random() * 500);
  // Responds if !doogal is said in chat.
  if (text.indexOf("!doogal") > -1){
    sendText(script[chooseText()]);
  }
  // Responds to a random message, occurs every 500 messages on average.
  else if (randomNum == 27) {
    sendText(script[chooseText()]);
  }
}

// Required function for Google Scripts.
function doGet() {}
